version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    command: gunicorn --chdir backend BreakWordTrapsBackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod.local
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    command: celery -A BreakWordTrapsBackend worker -l info
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env.prod.local
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db.local

  redis:
    image: "redis:alpine"

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: