services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=breakwordtraps
      - POSTGRES_USER=breakwordtrapsuser
      - POSTGRES_PASSWORD=breakwordtrapspassword
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A BreakWordTrapsBackend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - POSTGRES_DB=breakwordtraps
      - POSTGRES_USER=breakwordtrapsuser
      - POSTGRES_PASSWORD=breakwordtrapspassword
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=breakwordtraps
      - POSTGRES_USER=breakwordtrapsuser
      - POSTGRES_PASSWORD=breakwordtrapspassword

  redis:
    image: "redis:alpine"

volumes:
  postgres_data: